# Generated by Django 6.0.5 on 2026-08-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_erp_accounting_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
