# Generated by Django 6.0.8 on 2026-10-06 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_booking_additional_venues'),
        ('core', '0012_usersettings_show_hijri_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pricing_unit', models.CharField(choices=[('PER_EVENT', 'Per event'), ('PER_GUEST', 'Per guest'), ('PER_HOUR', 'Per hour')], default='PER_EVENT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MH service',
                'verbose_name_plural': 'MH — Services',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_booking_9deb2e_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_tenant__f0a288_idx',
            old_name='bookings_tenant_status_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_tenant__f7b16c_idx',
            old_name='bookings_tenant_event_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_start_d_94c02c_idx',
            old_name='bookings_bo_start_d_3e8155_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_custome_59c648_idx',
            old_name='bookings_customer_idx',
        ),
        migrations.AddField(
            model_name='hallservice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_services', to='core.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='hallservice',
            unique_together={('tenant', 'code')},
        ),
    ]
