# Generated by Django 6.0.8 on 2026-10-06 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0022_hall_service'),
        ('core', '0012_usersettings_show_hijri_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('include_in_bill', models.BooleanField(default=True, help_text='When true, quantity × unit price is added to the booking bill.')),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='bookings.booking')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_allocations', to='bookings.hallservice')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_services', to='core.tenant')),
            ],
            options={
                'verbose_name': 'MH booking service',
                'verbose_name_plural': 'MH — Booking services',
                'unique_together': {('booking', 'service')},
            },
        ),
    ]
