# Generated by Django 6.0.5 on 2026-08-18 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_erp_accounting_audit'),
        ('core', '0009_erp_accounting_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('POST', 'Post'), ('REVERSE', 'Reverse'), ('VOID', 'Void'), ('CREATE', 'Create'), ('UPDATE', 'Update')], max_length=20)),
                ('entity_type', models.CharField(max_length=40)),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.tenant')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', 'entity_type', 'entity_id'], name='audit_logs_tenant__742625_idx'), models.Index(fields=['tenant', 'created_at'], name='audit_logs_tenant__0b1a88_idx')],
            },
        ),
    ]
