# Generated by Django 6.0.5 on 2026-08-29 08:56

from django.conf import settings
from django.db import migrations, models


def backfill_active_source_keys(apps, schema_editor):
    """Assign active_source_key to POSTED non-reversed source journals (newest wins on dupes)."""
    JournalEntry = apps.get_model('accounting', 'JournalEntry')
    skip = {'manual', 'reversal'}
    seen = set()
    qs = (
        JournalEntry.objects.filter(status='POSTED', active_source_key__isnull=True)
        .exclude(source_type__in=skip)
        .exclude(source_id__isnull=True)
        .order_by('-id')
    )
    for entry in qs.iterator():
        key = f'{entry.source_type}:{entry.source_id}'
        tenant_key = (entry.tenant_id, key)
        if tenant_key in seen:
            continue
        # Skip if a reversal already exists for this entry
        if JournalEntry.objects.filter(
            reversed_entry_id=entry.pk, status='POSTED'
        ).exists():
            continue
        seen.add(tenant_key)
        JournalEntry.objects.filter(pk=entry.pk).update(active_source_key=key)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_bookkeeping_module'),
        ('core', '0009_erp_accounting_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='active_source_key',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
        migrations.RunPython(backfill_active_source_keys, noop_reverse),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(
                condition=models.Q(('active_source_key__isnull', False)),
                fields=('tenant', 'active_source_key'),
                name='uniq_journal_active_source_key',
            ),
        ),
    ]
