# Generated by Django 6.0.5 on 2026-08-29 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_bookkeeping_module'),
        ('finance', '0004_erp_accounting_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='expense',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='accounting.bankaccount'),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_through',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('AP', 'Accounts Payable')], default='CASH', max_length=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='accounting.vendor'),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_payments', to='accounting.bankaccount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_no',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
