# Generated by Django 6.0.5 on 2026-08-29 08:56

from django.conf import settings
from django.db import migrations, models


def backfill_receipt_numbers(apps, schema_editor):
    """Ensure non-blank receipt_no before unique constraint; keep existing values."""
    from django.db.models import Q

    Payment = apps.get_model('finance', 'Payment')
    for payment in Payment.objects.filter(Q(receipt_no='') | Q(receipt_no__isnull=True)).iterator():
        candidate = f'RCP-{payment.pk:06d}'
        # Avoid rare collision with an existing receipt in the same tenant
        if payment.tenant_id and Payment.objects.filter(
            tenant_id=payment.tenant_id, receipt_no=candidate
        ).exclude(pk=payment.pk).exists():
            candidate = f'RCP-{payment.pk:06d}-T{payment.tenant_id}'
        Payment.objects.filter(pk=payment.pk).update(receipt_no=candidate)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_hardening_constraints'),
        ('bookings', '0011_bookkeeping_module'),
        ('core', '0009_erp_accounting_audit'),
        ('finance', '0005_bookkeeping_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(backfill_receipt_numbers, noop_reverse),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(('receipt_no', ''), _negated=True),
                    ('receipt_no__isnull', False),
                    ('tenant__isnull', False),
                ),
                fields=('tenant', 'receipt_no'),
                name='uniq_payment_tenant_receipt_no',
            ),
        ),
    ]
