# Generated by Django 5.2.16 on 2026-08-18 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guesthouse', '0017_unit_media_and_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghexpense',
            name='status',
            field=models.CharField(choices=[('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='POSTED', max_length=20),
        ),
        migrations.AddField(
            model_name='ghexpense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='staypayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='staypayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='staypayment',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('FAILED', 'Failed'), ('VOIDED', 'Voided')], default='COMPLETED', max_length=20),
        ),
        migrations.AlterField(
            model_name='staypayment',
            name='stay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='guesthouse.staybooking'),
        ),
    ]
