# Generated by Django 5.2.16 on 2026-08-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_default_check_in_6pm'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='default_currency',
            field=models.CharField(default='PKR', max_length=8),
        ),
        migrations.AddField(
            model_name='tenant',
            name='overtime_rate_per_hour',
            field=models.DecimalField(decimal_places=2, default=5000, help_text='Hall overtime charge per hour.', max_digits=12),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=0.05, help_text='Sales tax rate, e.g. 0.0500 for 5%.', max_digits=6),
        ),
    ]
